version: '3.8'

services:
  agentzero:
    build: .
    container_name: agentzero-ollama
    ports:
      - "11434:11434"  # Ollama API
      - "8501:8501"    # Streamlit Web UI
    volumes:
      - ollama_data:/root/.ollama
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  ollama_data:
    driver: local

networks:
  default:
    name: agentzero-network

